- name: "Update homebrew"
  homebrew:
    update_homebrew: yes
  tags: homebrew

- name: "Install homebrew packages"
  homebrew:
    update_homebrew: no
    name: "{{ item }}"
    state: latest
  with_items:
    - abook
    - ansible
    - aspell
    - bash
    - bookloupe
    - colordiff
    - composer
    - coreutils
    - cpanminus
    - cscope
    - ctags
    - ctop
    - cvs
    - euler-py
    - exercism
    - exif
    - exiftool
    - fswatch
    - git
    - git-lfs
    - gnupg
    - gnupg2
    - gpg-agent
    - graphviz
    - grip
    - groff
    - gron
    - highlight
    - htop
    - httpd
    - httpie
    - hugo
    - ipython
    - jhead
    - jid
    - jq
    - lua
    - luajit
    - lynx
    - md5sha1sum
    - mercurial
    - micro
    - mkcert
    - mobile-shell
    - mosh
    - most
    - mtr
    - multimarkdown
    - mutt
    - nethogs
    - nginx
    - ngrep
    - nmap
    - node
    - nvm
    - perl
    - php70
    - php@7.0
    - postgresql
    - python
    - python3
    - python@2
    - reattach-to-user-namespace
    - ruby
    - shyaml
    - sipcalc
    - slackcat
    - sloccount
    - socat
    - telnet
    - the_silver_searcher
    - tidy-html5
    - tig
    - tmux
    - tnef
    - tree
    - unrar
    - vim
    - watchman
    - wget
    - xz
    - yamllint
    - yarn
    - youtube-dl
  notify: "Brew administrative tasks"
  tags: homebrew

- name: "Upgrade homebrew packages"
  homebrew:
    update_homebrew: no
    upgrade_all: yes
  notify: "Brew administrative tasks"
  tags: homebrew
