- name: "Update homebrew"
  homebrew:
    update_homebrew: yes
  tags:
    - homebrew

- name: "Install homebrew packages"
  homebrew:
    update_homebrew: no
    name: "{{ item }}"
    state: latest
  with_items:
    - abook
    - ansible
    - aspell
    - bash
    - bookloupe
    - colordiff
    - composer
    - coreutils
    - cpanminus
    - cscope
    - ctags
    - ctop
    - cvs
    - euler-py
    - exercism
    - exif
    - exiftool
    - fswatch
    - git
    - git-lfs
    - gnupg
    - gnupg2
    - gpg-agent
    - graphviz
    - grip
    - groff
    - gron
    - highlight
    - htop
    - httpd
    - httpie
    - hugo
    - ipython
    - jhead
    - jid
    - jq
    - lua
    - luajit
    - lynx
    - md5sha1sum
    - mercurial
    - micro
    - mkcert
    - mobile-shell
    - mosh
    - most
    - mtr
    - multimarkdown
    - mutt
    - nethogs
    - nginx
    - ngrep
    - nmap
    - node
    - nvm
    - perl
    - php70
    - php@7.0
    - postgresql
    - python
    - python3
    - python@2
    - reattach-to-user-namespace
    - ruby
    - shyaml
    - sipcalc
    - slackcat
    - sloccount
    - socat
    - telnet
    - the_silver_searcher
    - tidy-html5
    - tig
    - tmux
    - tnef
    - tree
    - unrar
    - vim
    - watchman
    - wget
    - xz
    - yamllint
    - yarn
    - youtube-dl
  notify: "Brew administrative tasks"
  tags:
    - homebrew

- name: "Upgrade homebrew packages"
  homebrew:
    update_homebrew: no
    upgrade_all: yes
  notify: "Brew administrative tasks"
  tags:
    - homebrew

- name: "Install hiera-eyaml gem"
  when: ansible_os_family == "Darwin"
  gem:
    name: hiera-eyaml
    state: present
    executable: /usr/local/bin/gem
    user_install: no
  tags:
    - puppet

- name: "Install hiera-eyaml-gpg gem"
  when: ansible_os_family == "Darwin"
  gem:
    name: hiera-eyaml-gpg
    state: present
    executable: /usr/local/bin/gem
    user_install: no
  tags:
    - puppet

- name: "Install gpgme gem"
  when: ansible_os_family == "Darwin"
  gem:
    name: gpgme
    state: present
    executable: /usr/local/bin/gem
    user_install: no
  tags:
    - puppet

- name: "Install yard gem"
  when: ansible_os_family == "Darwin"
  gem:
    name: yard
    state: present
    executable: /opt/puppetlabs/puppet/bin/gem
    user_install: no
  become: true
  tags:
    - puppet

- name: "Install puppet-strings gem"
  when: ansible_os_family == "Darwin"
  gem:
    name: puppet-strings
    state: present
    executable: /opt/puppetlabs/puppet/bin/gem
    user_install: no
  become: true
  tags:
    - puppet

- name: "Install Jupyter Python environment"
  when: ansible_os_family == "Darwin"
  pip:
    name: "{{ item }}"
    extra_args: "--upgrade"
    executable: /usr/local/bin/pip3
  with_items:
    - pip
    - jupyter
    - pyzmq
  tags:
    - python
    - jupyter

- name: "Install Jupyter JavaScript/Node.js environment"
  when: ansible_os_family == "Darwin"
  yarn:
    name: ijavascript
    global: yes
    production: yes
    state: latest
  tags:
    - nodejs
    - jupyter
  notify: "Install jupyter nodejs"
