- name: "Install zsh files"
  copy:
    src: "{{ dotfiles }}/{{ item }}"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    mode: 0644
  with_items:
    - zlogin
    - zlogout
    - zshenv
    - zshrc
  tags:
    - zsh

- name: "Install oh-my-zsh directory"
  synchronize:
    src: "{{ dotfiles }}/oh-my-zsh/"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh"
    delete: yes
    rsync_opts:
      - "--exclude=.git"
  tags:
    - zsh
