- name: "Install version-control configurations"
  copy:
    src: "{{ dotfiles }}/{{ item }}"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    mode: 0644
  with_items:
    - gitconfig
    - gitignore
    - hgrc
    - cvsrc
  tags: vcs

- name: "Install git-credential-osxkeychain"
  when: ansible_os_family == "Darwin"
  copy:
    src: "{{ dotfiles }}/git-credential-osxkeychain"
    dest: /usr/local/bin/git-credential-osxkeychain
    mode: 0755
  tags: vcs

- name: "Set up git-credential-osxkeychain"
  when: ansible_os_family == "Darwin"
  command: git config --global credential.helper osxkeychain
  tags: vcs
