- name: "Create .gnupg directory"
  file:
    path: "{{ ansible_user_dir }}/.gnupg"
    state: directory
    mode: 0700
  tags:
    - gpg
    - gnupg

- name: "Install gnupg config file"
  copy:
    src: "{{ dotfiles }}/gpg.conf"
    dest: "{{ ansible_user_dir }}/.gnupg/gpg.conf"
    mode: 0600
  tags:
    - gpg
    - gnupg
