- name: Clean up brew
  command: brew cleanup
  listen: "Brew administrative tasks"

- name: Restart brew services
  command: brew services restart --all
  listen: "Brew administrative tasks"

- name: Install pylint
  command: pip3 install pylint
  listen: "Brew administrative tasks"

- name: Install jupyter nodejs
  command: ijsinstall
  listen: "Install jupyter nodejs"

- name: Install nodebook service definition
  command: launchctl load /Users/dan/Library/LaunchAgents/com.tangledhelix.nbk.plist
  listen: "Set up nodebook"

