- name: "Install misc files"
  copy:
    src: "{{ dotfiles }}/{{ item }}"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    mode: 0644
  with_items:
    - colordiffrc
    - emacs
    - ircrc
    - perldb
    - perltidyrc
    - pgclirc
    - pryrc
    - psqlrc
    - screenrc
    - tcshrc
    - tmux.conf
  tags:
    - misc

- name: "Install terminfo files"
  when: ansible_os_family == "Solaris"
  synchronize:
    src: "{{ dotfiles }}/terminfo/"
    dest: "{{ ansible_user_dir }}/.terminfo"
    delete: yes
  tags:
    - misc
