- name: "Install misc files"
  copy:
    src: "{{ dotfiles }}/{{ item }}"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    mode: 0644
  with_items:
    - colordiffrc
    - emacs
    - ircrc
    - perldb
    - perltidyrc
    - pgclirc
    - pryrc
    - psqlrc
    - screenrc
    - tcshrc
    - tmux.conf

- name: "Install terminfo files"
  when: ansible_os_family == "Solaris"
  synchronize:
    src: "{{ dotfiles }}/terminfo/"
    dest: "{{ ansible_user_dir }}/.terminfo"
    delete: yes

- name: "Install hiera-eyaml gem"
  when: ansible_os_family == "Darwin"
  gem:
    name: hiera-eyaml
    state: present
    executable: /usr/local/bin/gem
    user_install: no
  tags: eyaml

- name: "Install hiera-eyaml-gpg gem"
  when: ansible_os_family == "Darwin"
  gem:
    name: hiera-eyaml-gpg
    state: present
    executable: /usr/local/bin/gem
    user_install: no
  tags: eyaml

- name: "Install gpgme gem"
  when: ansible_os_family == "Darwin"
  gem:
    name: gpgme
    state: present
    executable: /usr/local/bin/gem
    user_install: no
  tags: eyaml

- name: "Create .gnupg directory"
  file:
    path: "{{ ansible_user_dir }}/.gnupg"
    state: directory
    mode: 0700
  tags: gpg

- name: "Install gnupg config file"
  copy:
    src: "{{ dotfiles }}/gpg.conf"
    dest: "{{ ansible_user_dir }}/.gnupg/gpg.conf"
    mode: 0600
  tags: gpg

- name: "Install yard gem"
  when: ansible_os_family == "Darwin"
  gem:
    name: yard
    state: present
    executable: /opt/puppetlabs/puppet/bin/gem
    user_install: no
  become: true
  tags: puppet

- name: "Install puppet-strings gem"
  when: ansible_os_family == "Darwin"
  gem:
    name: puppet-strings
    state: present
    executable: /opt/puppetlabs/puppet/bin/gem
    user_install: no
  become: true
  tags: puppet

