- name: "Install vimrc"
  copy:
    src: "{{ dotfiles }}/vimrc"
    dest: "{{ ansible_user_dir }}/.vimrc"
    mode: 0644

- name: "Install vim directory"
  synchronize:
    src: "{{ dotfiles }}/vim/"
    dest: "{{ ansible_user_dir }}/.vim"
    delete: yes
    rsync_opts:
      - "--exclude=.git"
