- hosts: all
  vars:
    dotfiles: "{{ playbook_dir }}/.."
  roles:
    - { role: zsh }
    - { role: vcs }
    - { role: misc }
    - { role: vim }
    - { role: bash }
    - { role: scripts }

- hosts: macos
  roles:
    - { role: homebrew }
